### ISSUE TITLE
Make the value proposition of this library more clear

### ISSUE THREAD

**Issue by MrPowers** [ballista-compute/ballista#113]
I am really excited about this project.  Always following the code you write closely!

I saw [this post on Reddit](https://www.reddit.com/r/apachespark/comments/g47oyq/rust_bindings_for_apache_spark/) and the Rust keybindings look really cool.  A bit of a sales pitch would help me understand why I should use this feature and how it'll make my life better ;)

I think a sales pitch could also help the README.  Tell users why this library will help them and make their existing Spark workflows better.

Let me know if this sounds good and I can try to send you a PR.  Thanks!

**Comment by andygrove** [comment]
Yes, I agree. It's complex because this project has different audiences and is aiming to provide multiple things with value.

The things that have some value now (IMO) are:

- JVM-native query engine. Useful for anyone wanting to embed a query engine in their Java application or service.
- Rust-native query engine. Useful for anyone wanting to embed a query engine in their Rust application or service. This doesn't add any much value above DataFusion currently, but that may change soon.
- Demonstrates an architecture for interoperability ... not much immediate value yet, beyond demonstrating how Rust can co-exist with Spark

Future value will come from having the distributed query planner and scheduler. That is when this project potentially becomes a lot more interesting. I hope to get this working over the next few months.

**Comment by andygrove** [comment]
Do you think it would be better to split this project into multiple repositories? That way it would be less confusing for people who are interested in just one aspect of it. For example, people interested in a JVM query engine library would just look at the "ballista-compute/jvm-query-engine" repo.

**Comment by andygrove** [comment]
Please see the new user guide and README, where I have attempted to make the value proposition clearer:

https://ballistacompute.org/docs/
https://github.com/ballista-compute/ballista

**Comment by andygrove** [comment]
I think this was done now

**Comment by MrPowers** [comment]
@andygrove - any chance you could add an example that shows how to read 4 CSVs in parallel, do a repartition and then write out 2 Parquet files?  I'd like to write a blog post with that "distributed computing hello world" example to promote this project, thanks!

**Comment by andygrove** [comment]
@MrPowers yes, absolutely. DatraFusion has a PR open for hash partitioning which will allow Ballista to implement the equivalent of Spark's shuffle hash join and that will enable much better scalability. I am planning on writing this up in detail for my book so maybe I'll draft out some content on this as well and send it to you so you can use it in your post if that is helpful.
