### ISSUE TITLE
[JVM] Make version number available in jar files

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#129]
It would be good to have Gradle write the version number (and other build info) to the manifest of the executor jar so that the executor can print its version number on startup. 

This applies to both the jvm and spark executor.

**Comment by stspyder** [comment]
Hi, long time lurker here. I finally found some time to contribute. Can I take this?

**Comment by andygrove** [comment]
Yes, please do!

**Comment by stspyder** [comment]
So I ran into a complication. Both `ballista-jvm` and `ballista-spark` contains a sub project named `executor` that produces a JAR in the same name (`executor.jar`). As `spark/executor` depends on `jvm/executor`, the gradle application plugin now has to put both JARs - with the same name, in the same directory (lib) when packing tar/zip for `spark/executor`. As packing is done, one gets replaced by the other and leads to `java.lang.ClassNotFoundException`. 

This error doesnt occur in current master, because as `jvm/executor` is published to maven, it gets renamed to `executor-VERSION.jar`. But as I included versioning to all subprojects, I started to notice this issue.

The most straight forward solution is to rename the sub-project. But if you like the consistent naming that projects have, then we'd have to have gradle build a jar with a slightly different name (like spark-executor-VERSION.jar). But then we'd have to change the artifact ID when publishing this jar and wont be consistent with the directory name.

What do you suggest?

**Comment by andygrove** [comment]
Closed in https://github.com/ballista-compute/ballista/pull/169
