### ISSUE TITLE
[JVM] Use a robust CSV library

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#136]
The JVM query engine currently has some simple proprietary code for reading CSV files and we should use an established library like Apache Commons CSV or whatever Hadoop or Spark uses. We need to run some benchmarks before choosing a library to make sure we're not sacrificing on performance.

**Comment by zznq** [comment]
I came across this repo that has already run some benchmarks. https://github.com/univocity/csv-parsers-comparison

It looks like OpenCSV and Apache CSV are both fairly slow on the 3 million row test file. The faster ones look to be lesser known libraries and perhaps there is a little bit of bias in the benchmarks since the fastest one is from the univocity themselves.

Not sure if this is enough to make a decision from.....

For what it's work it does look like Spark is using the `UnivocityParser`, so maybe that is the one to go with.

**Comment by andygrove** [comment]
Thanks @zznq Univocity sounds good to me.

**Comment by andygrove** [comment]
This was closed by https://github.com/ballista-compute/ballista/pull/165
