### ISSUE TITLE
Implement SortExec

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#213]
Sort is implemented in DataFusion so should be simple to fork and add support in this project.

Note that the long term plan is to use DataFusion executors once they support async and are extensible.

**Comment by jorgecarleitao** [comment]
Dont we need this to run TPCH 1, #214? there is an order by there.

**Comment by andygrove** [comment]
Yes, I will need to add that. Filter and sort are commented out for the
moment in tpch q1.

**Comment by jorgecarleitao** [comment]
Isn't the filter added in #239 ? Or we also need to work out the SQL parsing / df? Trying to understand because I though that #239 fixed that. Otherwise, IMO it would be helpful to have more clarity on the DoD of the issues.

For this one, I can take this one if you want, but I need to know what the DoD is:
* the physical plan
* integration with the DataFrame API
* tests
* Add to TPC-H Query 1 example
* ?

**Comment by andygrove** [comment]
Sorry, was replying on phone. TPCH Q1 is implemented except for the filter and sort. I hit an issue [1] when adding a filter.

Sort needs to be ported over from DataFusion still.

[1] https://github.com/ballista-compute/ballista/issues/251

**Comment by andygrove** [comment]
For DoD ... I agree. I need to start planning and communicating more now that it isn't just me. I am trying to get to a 0.3.0 release as an MVP. It would be nice to run the full TPCH query 1 but not critical.

**Comment by andygrove** [comment]
This was completed
