### ISSUE TITLE
Executors should expose prometheus metrics

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#283]
By exposing metrics to prometheus we can set up beautiful dashboards that make it easy to monitor performance metrics and this is really helpful when benchmarking.

I would recommend using this crate.

https://crates.io/crates/rocket_prometheus

The simplest metric to expose right now would be # of concurrent tasks.

**Comment by sd2k** [comment]
As the author of rocket_prometheus I love to see anyone recommending that crate 😄 but I think the ecosystem has moved on slightly from when this issue was written, and it might be more appropriate to handle metrics using [OpenTelemetry](https://docs.rs/opentelemetry/0.12.0/opentelemetry/index.html), so that metrics can be tracked and exported to various formats rather than being constrained to just Prometheus. There's a better explanation [in the docs](https://docs.rs/opentelemetry/0.12.0/opentelemetry/global/index.html#global-metrics-api)!
