### ISSUE TITLE
Rust CI tests are all running twice (push + pull_request)

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#290]
Rust CI tests are all running twice (push + pull_request)

**Comment by jorgecarleitao** [comment]
My understanding of what we have:

1. When someone pushes to a branch the tests run
    So that the person can run the tests on CI before pull requesting

2. When a pull request opens the tests run
    So that reviewers, committers and author have a common source of truth

3. When a pull request is merged to a branch the tests run
    So that our branches are always tested
 
I.e. the tests run three times: one on push of a branch in whatever repo, one on the creation of a PR and one on merge to the base repo. AIFAK you only see 2 of these because the step 1 happens on the fork, not on the base repo.

If we remove step 1, users will have to PR to trigger tests to run. If we remove step 2, I am not sure github will mark the tests as "passing" on the PR. if we remove step 3, we lose CI/CD on main.

I would prefer that tests would be attached to commit hashs. However, I do not think that github can assume that because of how workflows are designed: the workflows receive environment variables that are dependent on git info (e.g. $GITHUB_REF) and those variables change the testing runtime. AFAIK this is the same design that gitlab uses.
