### ISSUE TITLE
Introduce abstractions for clusters, executor groups, executors

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#303]
The Ballista scheduler currently assumes that there is a single cluster, consisting of one of more executor processes identified by `host:port` that communicate over TCP.

In the future, we will want to support other types of environment, such as a "local mode" which uses in-process executors, or MPI [1].

This issue is to track design discussions around this topic.

[1] https://en.wikipedia.org/wiki/Message_Passing_Interface

**Comment by kyprifog** [comment]
Curious when you mention MPI in this context would it be just another option for establishing clusters or would this make ballista more of the vein of bridging the gap between the HPC/MPI and Spark Data intensive communities like Nikolay Malitsky talks about the Spark MPI project?  I'm really interested in the later for its application to scaling reinforcement learning.

**Comment by jedbrown** [comment]
It would be both, but mostly the latter. This issue spawned from a conversation on the Ballista discord. You could [start here](https://discord.com/channels/735486030626422884/735486030626422888/739119995501674529), but I'll excerpt the main parts below to consolidate going forward (expand details). At a high-level, I'm interested in interop with MPI libraries for things like multilevel SVM, data-sparse methods for GPR, Krylov methods and eigensolvers, and phsically-based models. My background is in computational science and engineering and I'd love to hear your thoughts on design and capability for this sort of platform.

 <details>

Andy:
> so ballista would interact with the communicator?

Jed: 
> That's what I'm trying to better understand. If Ballista could support the abstract concept, then I could add an MPI executor where we could have collective queries (implemented by reference algorithms for non-MPI executors versus using MPI's collectives).
In MPI, new processes can join by something like host:port (there is some higher level naming functionality), but once joined, we get a new communicator and identify each process by its rank (an integer). The potential obstacle is that creating a new communicator is a collective operation, so all ranks must participate.
A process can be part of many communicators (they're just simple objects), but if a process is blocked in IO or compute, we can't add a new rank. This adds some complexity to autoscaling. I don't think it's much of a problem when adding new ranks because the new ranks can be part of a separate communicator. But we can't have some members of a communicator blocked (IO or compute) and still let others leave.
This isn't a typical pattern in HPC, but seems like it would be routine for Ballista. One approach would be to keep communicators separate until a specific collective operation comes along, merge them for that operation, and drop the merged communicator after the collective operation (or sequence) completes.
(Let me know if this is too vague. I could draw pictures or write something more precise.)
I've mainly been thinking in terms of what MPI calls "intra-communicators", which is a symmetric group and what most all MPI libraries use. There are also "inter-communicators", which have two groups.
One model could be that the scheduler process never joins an intra-communicator (because it doesn't participate in compute), but manages inter-communicators and could mediate merging them (so they would share an intra-communicator and thus could do collective compute).
Each green vertex is an executor process. The fully-connected green clusters represent intracommunicators (that a library can run collective compute on). The blue represent intercommunicators, from which the scheduler (a single process for the foreseeable future?) interacts with executor groups (broadcasting/scattering inputs and gathering/reducing results). The scheduler can add or remove groups at any time (at the granularity of the whole group).
![](https://cdn.discordapp.com/attachments/735486030626422888/739134756310089768/Screenshot_20200801_085350.png)
One of the fully-connected green groups could be split (but all members must participate in the splitting) and then some could leave. New groups can arrive.
Merging would create the orange inter-comm and a new intra-comm of size 7 (yellow + green lines) to be able to do larger collective operations. All executors in the triangle and square groups would have to participate in the merge, but the pentagon group could be unaware. The smaller comms could persist so smaller queries could be run without dropping the orange one.
![](https://cdn.discordapp.com/attachments/735486030626422888/739136221669752882/Screenshot_20200801_090022.png)
We could skip these groups to begin with and just have scheduler talking to individual executor ranks. That would enable some RDMA and shared memory optimizations that might not take place (I don't know) in the current architecture, but doesn't really help collective MPI libs. I'm not sure how larger groups like in the diagrams would interact with other concepts of the platform.

Andy:
> so far, Ballista really just has the concept of a single cluster consisting of executor processes
it also has the concept of query stages, borrowed from Spark ... and Spark recently has new functionality called "query stage scheduling" or similar, where different stages of a query can target different nodes within a cluster ..
for example, a spark job may have both ETL and ML and they have different needs in terms of scale and resource type (like ML will likely need GPU nodes)

Jed:
> Yep, heterogeneous compute resources is another matter. Labels on inter-comms/groups seems like a scheduler feature.
</details>

**Comment by kyprifog** [comment]
Ok you've just piqued my interest in helping with this dramatically (lol).   So are you saying that individual executor threads (which I think is what you are saying a vertex represents in the above diagrams) would be dynamically scheduled on various executors as needed and that your concept of a "node" is actual more virtual determined by whether or not there is an MPI intra-communication channel opened up between specific threads (establishing shared memory between them), as you show in the second diagram where the orange designation interconnects all the nodes in those two subgraphs to look similar to the top one?

Essentially the MPI concept of intra communicators is virtual and dynamically determined and everything is kind of like an inter communicator by default?   This would be like the holy grail of HPC/spark unification type approaches if its what you are saying.   I'm less familiar with the MPI side so I would have to think more about how that would work.

**Comment by jedbrown** [comment]
Yeah, vertices were meant to be executor threads/processes. It's at the conceptualization phase now, but what I'd like to see is that the scheduler dispatches jobs to a communicator, which can work collectively. Note that a communicator might span many nodes, so there may not be "shared memory", but the communicator enables fast collective algorithms.

Communicators would be dynamic (though it would be useful to support static `MPI_COMM_WORLD` to simplify testing and use of conventional HPC resources, especially if using Ballista for pre/postprocessing of what could otherwise have been a stand-alone MPI-based program). I think it's important to support autoscaling, wherein a scheduler could decide it is over- or under-resourced and discharge or acquire new resources. The logic to do so would depend on the resource manager and billing granularity (e.g., in Kubernetes or SLURM), and must be extensible.

I'm glad to hear you're interested and have thought about Spark/MPI interop. If you and Andy can think about what this should look like from the Ballista/Spark perspective, I can contribute from the MPI/MPI-based libraries side.
