### ISSUE TITLE
Review use of HashMap in ColumnarBatch in branch-0.4

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#307]
I tried merging latest from main branch into branch-0.4 this morning and there was an issue with the changes in ColumnarBatch to use a HashMap of field name to column rather than just using a vec. I'd like to understand the motivation for this change and whether we can revert to using a vec.

The output from any operator should be deterministic and have a fixed schema, IMO, but maybe I am missing something?

**Comment by andygrove** [comment]
@jorgecarleitao When you have time, I'd like to get your thoughts on this.

**Comment by jorgecarleitao** [comment]
The motivation is that with the change in datafusion to not rely on the field index and instead use column names, makes HashMap a more common choice, since there is no natural order of column names.

AFAIK the output is deterministic, as `columns` are not a public interface of `ColumnarBatch` and all public interfaces are deterministic. In particular, `to_arrow` uses the `schema.fields()` to build a RecordBatch.

I am fine with changing it back to vectors, it just did not feel a natural data structure for an unsorted key. It does use more memory though.

I do not have strong feelings in either direction; it is an implementation detail of `ColumnarBatch`, anyway.

**Comment by andygrove** [comment]
Thanks. I'm not sure I have a strong opinion either, but would like to get the 0.3 code base aligned with 0.4 so we can merge the recent changes. I will try updating 0.3 to use hash map and see how it looks.

**Comment by andygrove** [comment]
Hi @jorgecarleitao Now that 0.3.0 is released, I created a branch-0.3 for ongoing 0.3 dev (if needed) and the main branch is now 0.4.0 using latest Arrow.

I renamed the `branch-0.4` branch to `branch-0.4-wip` because it still had the changes around hashmap instead of vec, which I had trouble reconciling. It also has changes to remove names from the physical plan, but now that we are using latest Arrow, I think we should focus on using the DataFusion physical plan (and improving DataFusion based on what we have learned so far in Ballista).

What do you think?

**Comment by jorgecarleitao** [comment]
@andygrove , perfect, let's do that. I can take a look at branch-0.4-wip and fix it or revert to vec if it is too much of an hassle.

I have not been touching the physical plans on purpose as I think that you have a better grasp on what we need to do on DataFusion side. However, feel free to ping me to take some of the tasks there. One idea is for you to write a canonical PR to one of the physical plans, which I can use as inspiration to convert other plans.

If this is a big change (i.e. an all or nothing change, which is typical in sync/async stuff), it may be beneficial to have a separate branch that we can both push or PR to. Your call.

**Comment by jorgecarleitao** [comment]
I am working on the branch-0.4-wip. My goal is to rebase it on top of master.

I now understand why it is difficult to rebase :)

We moved the compilation of expressions from the `ExecutionPlan::new` to inside `async fn execute` for all operators. I suspect that this is because we want to easily serialize `ExecutionPlan`, and thus we should avoid having `dyn` on any struct.

In general, I agree with this. However, we still need to be able to infer the schema of the operator on `new`. The current issue is that logical expressions do not have `nullable` (only the physical expression has it), and thus we cannot correctly infer the nullability of the output schema, given an input schema, without compiling the expressions.

DataFusion currently "cheats" (bugs?), by infering the schema from a Logical expression to always be nullable, and then adjust the schema after compiling the physical expressions. The offending line is here: https://github.com/apache/arrow/blob/db9185e889047279314888cca94b6585e7ca11e7/rust/datafusion/src/logicalplan.rs#L294, where there is a `true` on the last argument.

I believe that this is a limitation of `logical_plan::Expr`, as we can't correctly infer the complete schema from them alone: we always have to compile the physical expression to get the nullability detail right. From a conceptual point of view, nullability should inferable from a logical expression and input schema alone.

My suggestion is to move all `nullable` from the physical plans to the logical plans on DataFusion. This way, we can correctly construct output schemas from logical expressions alone, thus also solving our issue here.

What do you think, @andygrove ?

**Comment by andygrove** [comment]
This is an old discussion that has since been resolved
