### ISSUE TITLE
Add support for Parquet files that are partitioned on keys

### ISSUE THREAD

**Issue by dantodor** [ballista-compute/ballista#335]
Is it possible to open in Ballista ( JVM library ) a folder containing Parquet files, instead of a specific file ?
Exactly like you mention in your book, I have a structure with /year=xxxx/month=yy/day=zz .

**Comment by andygrove** [comment]
I just checked and that feature has not been implemented yet in the JVM library. It would certainly be nice to see this added. As a first step I would suggest changing `org.ballistacompute.datasource.ParquetDataSource` to have a list of filenames rather than one filename, and have a constructor that takes a path and checks if the path represents a file or a directory, and in the directory case it would recursive to find all the files.
