### ISSUE TITLE
What kubernetes constructs make most sense for the cluster?

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#35]
In the PoC, one pod and one service is created for each executor, but how should this really work? StatefulSet? Service with ReplicaSet?

I think the distributed query planner needs the ability to target specific executors (for things like data locality later on). Let's use this issue for the initial discussion.

**Comment by rrichardson** [comment]
StatefulSets have an interesting property, and that is [Stable Network Identities](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pods-in-a-statefulset)  
This is so that handlers for partitioned datasets can be accessed directly and consistently.  I think this would be the resource for executors. 

For queries and query planning,  I think a Custom Resource Definition for Query and one for client programs would make sense. Then the query planner is an operator which reads the query planner and executes the appropriate `Jobs` that consume the executors.

**Comment by andygrove** [comment]
New example uses stateful sets. Closing this issue. CRDs sound good and we should have separate issues for those.
