### ISSUE TITLE
Scheduler design question: How to distribute tasks to executors?

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#382]
The scheduler will break a query down into stages and tasks and then needs to send them to executors for execution.

The simplest approach is just to split the tasks into an equal number of chunks and then send them to executors on a round-robin basis by sending Flight actions to each executor and then wait for those requests to return a completion status (risk of network timeouts) or poll to check for status (inefficient).

One problem with this approach is that some executors may finish before others because the tasks can take variable lengths of time to complete.

Another option could be to write the tasks to etcd and implement a work queue design where each executor keeps pulling tasks until there are no more tasks. The scheduler can listen to etcd events to determine when the tasks are completed (when the queue is empty).

Using etcd would mean adding an etcd dependency to the Kubernetes deployment model.

Thoughts?

**Comment by chadbrewbaker** [comment]
My deployment  would be an EC2 Batch head node that spawns Batch Spot and AWS Lambda executors.  No Kubernetes. Preferable to package binaries as AWS EC2/Lambda zipfiles.  Keep the Kubernetes provisioning optional.

The https://github.com/StanfordSNR/gg task graph scheduler seems performant.  I have a side project of using a SMT solver to job shop schedule it for optimal cost within a runtime budget.

**Comment by edrevo** [comment]
Personally, I don't mind the etcd dependency that much (my guess is we'll probably need it for HA in the schedulers either way), but I'm not sure it is a requirement for a queue-based mechanism. Couldn't the scheduler implement an API to dispatch work in a queue-based manner instead of pre-assigning all of the chunks of work?

The way I see it, there are two strategies to dispatch tasks into executors:

1. The dispatching logic resides in the scheduler: for this route, I think it is better to have the workers and scheduler communicate via API. The assumption here is that centralizing the dispatch logic might allow you to perform more complicated allocations. Speculative execution comes to mind as something that could be easier to implement on the scheduler's side.
2. The dispatching logic resides in the executors: here, having an etcd interface between the workers and schedulers fits well, but I don't necessarily see it as a requirement. The assumption in this case is the inverse: the executor has better information to choose which task it wants to run. For example, data locality is something that might be easier to track on the worker's side.

Overall, I think that having a work queue in etcd as the interface between scheduler and executors for work allocation might be a less extensible design than the API.

**Comment by chadbrewbaker** [comment]
With a centralized scheduler - it also needs to know a bit about the executor pool and the data pool. In the AWS case you want Lambdas fired up in the same region where the corresponding data is on S3/EFS if possible. Might be able to generalize with Lat/Long of each executor to start with.  S3/EFS/MemCache even within a datacenter you are going to have storage tiers - start with a script that models the latency/bandwidth and stores it for later use?

**Comment by yordan-pavlov** [comment]
Ideally, ballista wouldn't depend on k8s or etcd - this would make it easier to try / learn ballista in a very simple environment without having to install potentially complicated dependencies.

But then, when deployed in production, ideally it would be highly available and scalable - so it would make sense to support a cluster of schedulers.
That's not really in conflict with the first requirement above - in a learning environment it would just be a cluster of a single scheduler.
And a cluster of schedulers would:
* avoid the scheduler becoming a bottleneck
* make the scheduler highly available
* possibly even enable online upgrades

Maintaining state in the scheduler cluster could be done, without adding external dependencies, using a raft library such as https://github.com/tikv/raft-rs.

**Comment by andygrove** [comment]
Thanks for the feedback so far. 

I agree that Kubernetes should be an optional dependencies. 

I am interested in exploring the raft idea more.

I hadn't really considered the batch use case yet.

It is clear that there are multiple deployment models that people will be interested in and it would be good to start tracking this.

**Comment by chadbrewbaker** [comment]
Passing a ulimit to the worker process and returning /usr/bin/time -v counters would be helpful too.  Allows resource hungry jobs to be dealt with using routine POSIX limits cross kernel instead of re-inventing another accounting system.
