### ISSUE TITLE
Implement to_proto support for Date32(Day)

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#392]
I am trying to run the tpch example and hit this error:

```
Error: General("logical_plan::to_proto() Unsupported data type Date32(Day)")
```

**Comment by pjmore** [comment]
I'm taking a look at this, I'll try to add all of the simple data types for now.

**Comment by pjmore** [comment]
So after taking a look at this it looks like doing this more work than I thought because currently the protobuf definitions don't have support for any non-primitive types. I'm working at adding this now but it'll take a little bit because a fair number of definitions need to be changed.

**Comment by bjcohen** [comment]
Heh, @pjmore I was looking at the same issue and came to the same conclusion in https://github.com/ballista-compute/ballista/pull/380#issue-556490329. Let me know if you need help or another pair of eyess.

**Comment by pjmore** [comment]
If you want to scan over the protobuf definitions to make sure I haven't done anything too weird that be awesome, although it is still very much a work in progress and might not be worth the time yet, the most recent changes I've made are [here](https://github.com/pjmore/ballista/tree/protobuf-type-support/rust/ballista/proto).  At the moment I've got about 90 errors in the code so it definitely won't compile at the moment. The main changes to support more complex types are:

1. Reworked ArrowType from enum to message allowing for nested and complex types, primitive types like bool are represented with an empty message. I'm not crazy about the ergonomics of this as it turns
``` arrow::datatypes::DataType::Bool => ArrowType::Bool  ```
into 
```  arrow::datatypes::DataType::Bool => ArrowType::Bool(EmptyMessage{}) ```
but it makes it possible to use a match statment over all supported types.
There are some additional message types added for the complex types like Dictionary, List, and FixedSizeBinary. This should may 1 to 1 with arrow::datatypes::DataType. 
2. Added enum named BasicDatafusionScalarType, not a final name haha, which represents the primitive types that datafusion can use as scalars. Done so that representing null literals is straight forward. This is missing 
3. Added Scalar value message which should map 1 to 1 with datafusion::scalar::ScalarValue. This one isn't done yet as the ScalarListValue message is currently incomplete.

**Comment by andygrove** [comment]
@pjmore Just fyi but I added quick and dirty support for Date32 as part of https://github.com/ballista-compute/ballista/pull/401 so that I can move ahead with trying to get the benchmarks and integration tests working, but I look forward to replacing this with the work you are doing here!
