### ISSUE TITLE
[Design] Release strategy and staying up to date with Arrow changes

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#433]
Arrow currently has releases every 2-3 months (this may become more frequent in the future). The Rust project currently uses the published Arrow 3.0.0 crates and this means that we can also release Ballista to crates.io

Arrow will continue to move forward with performance improvements and bug fixes and we need to decide on our strategy for staying up to date.

My proposal would be that we release Ballista 0.4.0 depending on Arrow 3.0.0 once the distributed query execution is working again, hopefully in the next few weeks, and then we can have a 0.4 branch where we could create patch releases if needed (unlikely at this stage).

Once 0.4.0 is released, we could have the main branch depend on the Arrow github repo so we pick up all the improvements, and then we release Ballista 0.5.0 once Arrow 4.0.0 is released, and so on.

**Comment by jameswinegar** [comment]
Having only started looking at Ballista recently. There's a few things to consider.

1. Do users have bare metal use cases that they'd want to leverage instead of container oriented.
2. Why couple the versioning so closely to arrow aside from making sure we maintain API compatibility and bring in performance enhancements. Is datafusion another thing to consider for the couple as we're really just extending it?
3. When would we want to "mature" in managing patch updates. Is that a 0.4 concern or a 1.0 concern? It feels like the later and although we don't think it's an issue is it something that we would want to set precedence on?
4. Container tags should be equivalent to release tags in git, and evented by a tag creation so people understand the code they're running. 

These questions are just for musing. I know for my use cases in the near future we'd likely want to take advantage of a bare metal solution and not container based. Additionally it isn't hard to just compile the project into a binary and manage it that way too.
