### ISSUE TITLE
Add support for Java columnar UDF

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#434]
I would like to be able to reference a Java UDF from a query plan. Here is a rough breakdown of the steps involved

- ballista.proto needs a definition of a Java UDF (classpath, class name, method name, and so on)
- Java Executor process that can receive a Java UDF physical plan and execute it
- BallistaContext needs a method for registering a Java UDF
- It needs to be possible to reference the Java UDF from the DataFrame API and logical plan. This may need changes to DataFusion, or may force us into forking the DataFrame and Logical Plan again.

**Comment by jorgecarleitao** [comment]
Good question.

I have done this in Python on DataFusion / single node. The code is here: https://github.com/jorgecarleitao/datafusion-python/blob/master/src/udf.rs#L15, but I do not think it is applicable because we would need to serialize a Rust closure, while here the hypothesis is that the udf is already on the node (right?)

My initial idea would be to use a custom physical node using DataFusion extension API, and have the planner plan replace any projection with a java udf by 2 projections, 1 in native rust, and 1 in java, each sent to their respective node.

However, I can see that we do not have an extension for _expressions_, only nodes, which means that it would likely not work with SQL, as we would have no way of mapping the SQL expression to a "java udf" (since there is none). It seems like a good feature for DataFusion, though: add support for custom expressions at the logical plan, that custom planners can plan differently.
