### ISSUE TITLE
Add option to store partition results in memory rather than streaming to disk

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#509]
The executor currently always streams partition results to disk. This is good for avoiding memory pressure but is expensive. The user may want to keep results in memory instead.

We should add an enum to the `ExecutionPartition` and `FetchPartition` protobuf actions specifying how to persist the results (disk or memory).

We will need to expose this functionality to the user through a configuration property that can be passed to `BallistaContext::remote()` in the `settings` argument.

**Comment by fitzoh** [comment]
Was thinking about an API like this with a disk and memory implementation, sound reasonable?

```rust
#[tonic::async_trait]
trait PartitionResultStore {
    async fn persist(
        &self,
        partition_id: &PartitionId,
        result: SendableRecordBatchStream,
    ) -> Result<PartitionStats, BallistaError>;

    async fn retrieve(&self, partition_id: &PartitionId) -> Result<FlightDataStream, BallistaError>;
}
```

Also, `ExecutePartition` looks like it currently returns the path as part of the response.
Is this important to maintain?


https://github.com/ballista-compute/ballista/blob/56fe5e5ff62f2cc174572291d939231866e8ce9c/rust/ballista/src/executor/flight_service.rs#L150-L151

**Comment by andygrove** [comment]
I've been thinking about this issue some more and I'm not sure if it is worth pursuing or not but I would be interested in hearing other people's opinions. If we do implement it, the design suggested here looks reasonable. The response would have to be updated to make `path` optional.

**Comment by edrevo** [comment]
I think memory mapped files are a good fit for this: since arrow has no serialization, then you can just write everything to the mmap file and let the kernel flush out to disk the pages that don't fit in memory. I believe this is more or less what Kafka does and they get great performance.

**Comment by edrevo** [comment]
>Also, ExecutePartition looks like it currently returns the path as part of the response.
> Is this important to maintain?

We should probably rename the variable to "output_id" or something similar. The fact that it is a path is irrelevant from the client's perspective. It's just used as an opaque blob to identify a specific output inside an executor.

**Comment by edrevo** [comment]
I've been thinking about this issue for the last couple of days. I referenced memory mapped files in a previous (now deleted) comment: mmap files isn't the answer here, unfortunately. I believe the easiest way to handle disk spilling would be to create the partition results in tmpfs (which is a virtual memory based file system). The Linux kernel would then keep as many pages in physical memory as it can and then swap to disk those that didn't fit. These pages would be evictable, so they wouldn't count towards the memory usage of the executor. Great! Sounds like that could work! However... K8S doesn't support running on swap-enabled systems, so that pretty much rules out this plan.

I do think that we should strive to get a design that doesn't rely on the user defining which piece of data needs to go to RAM vs disk. Maybe I am being overly ambitiousm but Ballista will have a lot of context as to what will be used next, how much free memory the node has and those kinds of things.
