### ISSUE TITLE
Add support for SortMergeJoin

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#596]
This is a bit of a placeholder but at some point, we should consider implementing sort-merge joins (see Wikipedia for algorithm [1]).

The benefit of adding this is that it reduces memory pressure because it isn't necessary to load one side of the join into memory.

[1] https://en.wikipedia.org/wiki/Sort-merge_join

**Comment by jorgecarleitao** [comment]
I have code for a physical node for this on the DataFusion side: I never PRed it because we have no use for it (as we have been loading everything in memory). The code is ~2 times slower than using DataFusion's sort, but it requires significantly less memory.

If there is a use-case here, I can try write a PR with it.

**Comment by andygrove** [comment]
Thanks, that would be really great. Memory pressure is a huge issue. We either need to implement this or [ShuffleHashJoin](https://github.com/ballista-compute/ballista/issues/595) (which would require hash partitioning support in DataFusion).
