### ISSUE TITLE
Improve task and job metadata

### ISSUE THREAD

**Issue by edrevo** [ballista-compute/ballista#614]
The task and job status we save in the scheduler state is currently lacking. See:

https://github.com/ballista-compute/ballista/blob/a0c609f3a43ed316df6c21c3e04ce7de726455d4/rust/ballista/proto/ballista.proto#L532-L543

And:

https://github.com/ballista-compute/ballista/blob/a0c609f3a43ed316df6c21c3e04ce7de726455d4/rust/ballista/proto/ballista.proto#L474-L484

The job status should include:
- Start time for the job (the moment it was queued)
- Finish time for the job (for the completed state)
- Number of pending/running/completed/failed tasks and stages (for the running state)

The task status should include:
- Start time for the task
- Finish time for the task (for the completed state)

**Comment by dashstander** [comment]
Hey, I'm interested in giving this issue a shot. Just want to make sure I more or less understand what you're asking. To get this to work I should:
1. Add the fields you mentioned to the task and job proto fields
2. Update the following functions to reference the correct data for serialization/deserialization
https://github.com/ballista-compute/ballista/blob/a0c609f3a43ed316df6c21c3e04ce7de726455d4/rust/ballista/src/scheduler/state/mod.rs#L95-L148
3. Update all of the places those functions are called to either save the proper metadata or change the print statements so that data is communicated.

That's what I'm seeing right now, but I'm brand new to the codebase. Would that be a decent place to start?

**Comment by edrevo** [comment]
Yep, you got it. Just modify the proto definitions and that will create a bunch of compile failures. Then you need to rinse and repeat until the compiler is happy.

**Comment by dashstander** [comment]
"make the compiler happy", sounds like a plan 👍

**Comment by edrevo** [comment]
Feel free to chunk this in different PRs if you want a more incremental approach. Thanks for taking a look at this!

**Comment by morpheyesh** [comment]
Is this still open or being worked on currently? :)
