### ISSUE TITLE
why only 1 executor works even I start 2 executors?

### ISSUE THREAD

**Issue by qiuzhanghua** [ballista-compute/ballista#649]
I use ballista 0.4.1, and
1. start etcd
```bash
/opt/etcd/etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://0.0.0.0:2379
```
Under ballista/rust
2. start scheduler
```bash
RUST_LOG=info target/release/scheduler --config-backend etcd --etcd-urls localhost:2379 --bind-host 0.0.0.0 --port 50050
```
3. start excecutor 1
```bash
RUST_LOG=info target/release/executor --bind-host 0.0.0.0 --port 50051 --scheduler-host localhost
```
4. start excecutor 2
```bash
RUST_LOG=info target/release/executor --bind-host 0.0.0.0 --port 50052 --scheduler-host localhost
```
Under ballista/rust/benchmarks/tpch
5. run benchmark
```bash
cargo run benchmark --host localhost --port 50050 --query 1 --path $(pwd)/data --format tbl --iterations 1
```
I find that only one executor runs.
scheduler log shows partitions = 1 as
```txt
CsvExec: /Users/daniel/workspace/ballista/rust/benchmarks/tpch/data/lineitem.tbl; partitions=1
```
@andygrove 
Thanks!

**Comment by andygrove** [comment]
Hi @qiuzhanghua. Currently, Ballista treats each file as one partition. Query fragments get executed with each executor handling one or more partitions. 

In order to make Ballista scale better when the input data only has a single partition, we would need to dynamically repartition the input files (which should not be hard now that DataFusion supports hash partitioning).
